// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: top_rating.proto

package com.moviecatalogservice.grpc;

/**
 * <pre>
 * The response message containing the greetings
 * </pre>
 *
 * Protobuf type {@code rating.Rating}
 */
public final class Rating extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:rating.Rating)
    RatingOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Rating.newBuilder() to construct.
  private Rating(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Rating() {
    moveId_ = "";
  }



  @Override
  @SuppressWarnings({"unused"})
  protected Object newInstance(
      UnusedPrivateParameter unused) {
    return new Rating();
  }

  @Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return RatingProto.internal_static_rating_Rating_descriptor;
  }

  @Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return RatingProto.internal_static_rating_Rating_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Rating.class, Rating.Builder.class);
  }

  public static final int MOVE_ID_FIELD_NUMBER = 1;
  private volatile Object moveId_;
  /**
   * <code>string move_id = 1;</code>
   * @return The moveId.
   */
  @Override
  public String getMoveId() {
    Object ref = moveId_;
    if (ref instanceof String) {
      return (String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      String s = bs.toStringUtf8();
      moveId_ = s;
      return s;
    }
  }
  /**
   * <code>string move_id = 1;</code>
   * @return The bytes for moveId.
   */
  @Override
  public com.google.protobuf.ByteString
      getMoveIdBytes() {
    Object ref = moveId_;
    if (ref instanceof String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (String) ref);
      moveId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int RATE_FIELD_NUMBER = 2;
  private int rate_;
  /**
   * <code>int32 rate = 2;</code>
   * @return The rate.
   */
  @Override
  public int getRate() {
    return rate_;
  }

  private byte memoizedIsInitialized = -1;
  @Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moveId_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, moveId_);
    }
    if (rate_ != 0) {
      output.writeInt32(2, rate_);
    }
    getUnknownFields().writeTo(output);
  }

  @Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(moveId_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, moveId_);
    }
    if (rate_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, rate_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @Override
  public boolean equals(final Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Rating)) {
      return super.equals(obj);
    }
    Rating other = (Rating) obj;

    if (!getMoveId()
        .equals(other.getMoveId())) return false;
    if (getRate()
        != other.getRate()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MOVE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getMoveId().hashCode();
    hash = (37 * hash) + RATE_FIELD_NUMBER;
    hash = (53 * hash) + getRate();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Rating parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rating parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rating parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rating parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rating parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Rating parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Rating parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Rating parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Rating parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Rating parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Rating parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Rating parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Rating prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the greetings
   * </pre>
   *
   * Protobuf type {@code rating.Rating}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:rating.Rating)
      RatingOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return RatingProto.internal_static_rating_Rating_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return RatingProto.internal_static_rating_Rating_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Rating.class, Rating.Builder.class);
    }

    // Construct using Rating.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @Override
    public Builder clear() {
      super.clear();
      moveId_ = "";

      rate_ = 0;

      return this;
    }

    @Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return RatingProto.internal_static_rating_Rating_descriptor;
    }

    @Override
    public Rating getDefaultInstanceForType() {
      return Rating.getDefaultInstance();
    }

    @Override
    public Rating build() {
      Rating result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @Override
    public Rating buildPartial() {
      Rating result = new Rating(this);
      result.moveId_ = moveId_;
      result.rate_ = rate_;
      onBuilt();
      return result;
    }

    @Override
    public Builder clone() {
      return super.clone();
    }
    @Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.setField(field, value);
    }
    @Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return super.addRepeatedField(field, value);
    }
    @Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Rating) {
        return mergeFrom((Rating)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Rating other) {
      if (other == Rating.getDefaultInstance()) return this;
      if (!other.getMoveId().isEmpty()) {
        moveId_ = other.moveId_;
        onChanged();
      }
      if (other.getRate() != 0) {
        setRate(other.getRate());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @Override
    public final boolean isInitialized() {
      return true;
    }

    @Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              moveId_ = input.readStringRequireUtf8();

              break;
            } // case 10
            case 16: {
              rate_ = input.readInt32();

              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private Object moveId_ = "";
    /**
     * <code>string move_id = 1;</code>
     * @return The moveId.
     */
    public String getMoveId() {
      Object ref = moveId_;
      if (!(ref instanceof String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        moveId_ = s;
        return s;
      } else {
        return (String) ref;
      }
    }
    /**
     * <code>string move_id = 1;</code>
     * @return The bytes for moveId.
     */
    public com.google.protobuf.ByteString
        getMoveIdBytes() {
      Object ref = moveId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        moveId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string move_id = 1;</code>
     * @param value The moveId to set.
     * @return This builder for chaining.
     */
    public Builder setMoveId(
        String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      moveId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string move_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMoveId() {
      
      moveId_ = getDefaultInstance().getMoveId();
      onChanged();
      return this;
    }
    /**
     * <code>string move_id = 1;</code>
     * @param value The bytes for moveId to set.
     * @return This builder for chaining.
     */
    public Builder setMoveIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      moveId_ = value;
      onChanged();
      return this;
    }

    private int rate_ ;
    /**
     * <code>int32 rate = 2;</code>
     * @return The rate.
     */
    @Override
    public int getRate() {
      return rate_;
    }
    /**
     * <code>int32 rate = 2;</code>
     * @param value The rate to set.
     * @return This builder for chaining.
     */
    public Builder setRate(int value) {
      
      rate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rate = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearRate() {
      
      rate_ = 0;
      onChanged();
      return this;
    }
    @Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:rating.Rating)
  }

  // @@protoc_insertion_point(class_scope:rating.Rating)
  private static final Rating DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Rating();
  }

  public static Rating getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Rating>
      PARSER = new com.google.protobuf.AbstractParser<Rating>() {
    @Override
    public Rating parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Rating> parser() {
    return PARSER;
  }

  @Override
  public com.google.protobuf.Parser<Rating> getParserForType() {
    return PARSER;
  }

  @Override
  public Rating getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

