// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: top_rating.proto

package com.moviecatalogservice.grpc;

public final class RatingProto {
  private RatingProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_TopRatingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_TopRatingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_Rating_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_Rating_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_rating_TopRatingReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_rating_TopRatingReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\020top_rating.proto\022\006rating\"#\n\020TopRatingR" +
      "equest\022\017\n\007user_id\030\001 \001(\t\"\'\n\006Rating\022\017\n\007mov" +
      "e_id\030\001 \001(\t\022\014\n\004rate\030\002 \001(\005\"1\n\016TopRatingRep" +
      "ly\022\037\n\007ratings\030\001 \003(\0132\016.rating.Rating2O\n\tT" +
      "opRating\022B\n\014getTopRating\022\030.rating.TopRat" +
      "ingRequest\032\026.rating.TopRatingReply\"\000B9\n\037" +
      "com.example.ratingsservice.grpcB\013RatingP" +
      "rotoP\001\242\002\006Ratingb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_rating_TopRatingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_rating_TopRatingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_TopRatingRequest_descriptor,
        new String[] { "UserId", });
    internal_static_rating_Rating_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_rating_Rating_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_Rating_descriptor,
        new String[] { "MoveId", "Rate", });
    internal_static_rating_TopRatingReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_rating_TopRatingReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_rating_TopRatingReply_descriptor,
        new String[] { "Ratings", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
