// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: top_rating.proto

package com.moviecatalogservice.grpc;

public interface RatingOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.Rating)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string move_id = 1;</code>
   * @return The moveId.
   */
  String getMoveId();
  /**
   * <code>string move_id = 1;</code>
   * @return The bytes for moveId.
   */
  com.google.protobuf.ByteString
      getMoveIdBytes();

  /**
   * <code>int32 rate = 2;</code>
   * @return The rate.
   */
  int getRate();
}
