// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: top_rating.proto

package com.moviecatalogservice.grpc;

public interface TopRatingReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.TopRatingReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .rating.Rating ratings = 1;</code>
   */
  java.util.List<Rating> 
      getRatingsList();
  /**
   * <code>repeated .rating.Rating ratings = 1;</code>
   */
  Rating getRatings(int index);
  /**
   * <code>repeated .rating.Rating ratings = 1;</code>
   */
  int getRatingsCount();
  /**
   * <code>repeated .rating.Rating ratings = 1;</code>
   */
  java.util.List<? extends RatingOrBuilder> 
      getRatingsOrBuilderList();
  /**
   * <code>repeated .rating.Rating ratings = 1;</code>
   */
  RatingOrBuilder getRatingsOrBuilder(
      int index);
}
