// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: top_rating.proto

package com.moviecatalogservice.grpc;

public interface TopRatingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:rating.TopRatingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   * @return The userId.
   */
  String getUserId();
  /**
   * <code>string user_id = 1;</code>
   * @return The bytes for userId.
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
